# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encrypter_decrypterUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblApdu = QtWidgets.QLabel(self.centralwidget)
        self.lblApdu.setGeometry(QtCore.QRect(20, 280, 61, 41))
        self.lblApdu.setAlignment(QtCore.Qt.AlignCenter)
        self.lblApdu.setWordWrap(True)
        self.lblApdu.setObjectName("lblApdu")
        self.lblCipherApdu = QtWidgets.QLabel(self.centralwidget)
        self.lblCipherApdu.setGeometry(QtCore.QRect(10, 450, 81, 16))
        self.lblCipherApdu.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCipherApdu.setWordWrap(True)
        self.lblCipherApdu.setObjectName("lblCipherApdu")
        self.lblFrameCounter = QtWidgets.QLabel(self.centralwidget)
        self.lblFrameCounter.setGeometry(QtCore.QRect(470, 30, 101, 71))
        self.lblFrameCounter.setWordWrap(True)
        self.lblFrameCounter.setObjectName("lblFrameCounter")
        self.txtFrameCounter = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFrameCounter.setGeometry(QtCore.QRect(580, 60, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtFrameCounter.setFont(font)
        self.txtFrameCounter.setMaxLength(8)
        self.txtFrameCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.txtFrameCounter.setObjectName("txtFrameCounter")
        self.lblKey = QtWidgets.QLabel(self.centralwidget)
        self.lblKey.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.lblKey.setObjectName("lblKey")
        self.txtKey = QtWidgets.QLineEdit(self.centralwidget)
        self.txtKey.setGeometry(QtCore.QRect(130, 30, 291, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtKey.setFont(font)
        self.txtKey.setMaxLength(32)
        self.txtKey.setAlignment(QtCore.Qt.AlignCenter)
        self.txtKey.setObjectName("txtKey")
        self.lblSceltaCifraDecifra = QtWidgets.QLabel(self.centralwidget)
        self.lblSceltaCifraDecifra.setGeometry(QtCore.QRect(440, 170, 91, 16))
        self.lblSceltaCifraDecifra.setObjectName("lblSceltaCifraDecifra")
        self.cmbCifraDecifra = QtWidgets.QComboBox(self.centralwidget)
        self.cmbCifraDecifra.setGeometry(QtCore.QRect(550, 170, 111, 22))
        self.cmbCifraDecifra.setObjectName("cmbCifraDecifra")
        self.btnMakeApdu = QtWidgets.QPushButton(self.centralwidget)
        self.btnMakeApdu.setGeometry(QtCore.QRect(730, 40, 161, 61))
        self.btnMakeApdu.setObjectName("btnMakeApdu")
        self.textApdu = QtWidgets.QTextEdit(self.centralwidget)
        self.textApdu.setGeometry(QtCore.QRect(100, 240, 781, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textApdu.setFont(font)
        self.textApdu.setObjectName("textApdu")
        self.textOutputApdu = QtWidgets.QTextEdit(self.centralwidget)
        self.textOutputApdu.setGeometry(QtCore.QRect(100, 400, 781, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textOutputApdu.setFont(font)
        self.textOutputApdu.setReadOnly(True)
        self.textOutputApdu.setObjectName("textOutputApdu")
        self.cmbClientServer = QtWidgets.QComboBox(self.centralwidget)
        self.cmbClientServer.setGeometry(QtCore.QRect(770, 170, 121, 22))
        self.cmbClientServer.setObjectName("cmbClientServer")
        self.lblClientServer = QtWidgets.QLabel(self.centralwidget)
        self.lblClientServer.setGeometry(QtCore.QRect(680, 170, 81, 20))
        self.lblClientServer.setObjectName("lblClientServer")
        self.lblLdn = QtWidgets.QLabel(self.centralwidget)
        self.lblLdn.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.lblLdn.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLdn.setObjectName("lblLdn")
        self.txtLdn = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLdn.setGeometry(QtCore.QRect(130, 90, 291, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtLdn.setFont(font)
        self.txtLdn.setMaxLength(32)
        self.txtLdn.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLdn.setObjectName("txtLdn")
        self.chbLdnHex = QtWidgets.QCheckBox(self.centralwidget)
        self.chbLdnHex.setGeometry(QtCore.QRect(20, 100, 81, 20))
        self.chbLdnHex.setObjectName("chbLdnHex")
        self.txtSystemTitle = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSystemTitle.setGeometry(QtCore.QRect(130, 150, 291, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtSystemTitle.setFont(font)
        self.txtSystemTitle.setMaxLength(34)
        self.txtSystemTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSystemTitle.setObjectName("txtSystemTitle")
        self.lblSystemTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblSystemTitle.setGeometry(QtCore.QRect(40, 150, 81, 16))
        self.lblSystemTitle.setObjectName("lblSystemTitle")
        self.txtAad = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAad.setGeometry(QtCore.QRect(130, 190, 291, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtAad.setFont(font)
        self.txtAad.setMaxLength(32)
        self.txtAad.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAad.setObjectName("txtAad")
        self.lblAad = QtWidgets.QLabel(self.centralwidget)
        self.lblAad.setGeometry(QtCore.QRect(70, 190, 31, 16))
        self.lblAad.setObjectName("lblAad")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openUserGuide = QtWidgets.QAction(MainWindow)
        self.openUserGuide.setObjectName("openUserGuide")
        self.menuHelp.addAction(self.openUserGuide)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DLMS APDU Encryption/Decryption  Ver - 0.0.4"))
        self.lblApdu.setText(_translate("MainWindow", "APDU"))
        self.lblCipherApdu.setText(_translate("MainWindow", "Cipher APDU"))
        self.lblFrameCounter.setText(_translate("MainWindow", "Frame Counter (4 Bytes)"))
        self.lblKey.setText(_translate("MainWindow", "AES-Key (16 Bytes)"))
        self.lblSceltaCifraDecifra.setText(_translate("MainWindow", "Cypher/Decyper"))
        self.btnMakeApdu.setText(_translate("MainWindow", "Generate APDU"))
        self.lblClientServer.setText(_translate("MainWindow", "Client/Server"))
        self.lblLdn.setText(_translate("MainWindow", "LDN (16 Bytes)"))
        self.chbLdnHex.setText(_translate("MainWindow", "Hex"))
        self.lblSystemTitle.setText(_translate("MainWindow", "System Title"))
        self.lblAad.setText(_translate("MainWindow", "AAD"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.openUserGuide.setText(_translate("MainWindow", "User Guide"))
